### Suche alle Filme
GET {{restUrl}}

### Suche nach dem Film anhand der ID
GET {{restUrl}}/1

### Suche nach dem Film anhand der ID und Versionsnummer
GET {{restUrl}}/1
If-None-Match: "0"

### Suche nach dem Film anhand des Namens
GET {{restUrl}}/?name=Verschollen

### Suche mit gültigem Rating
GET {{restUrl}}?rating=7

### Suche mit gültiger Filmart
GET {{restUrl}}?art=ACTION