@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [FilmController]
  [FilmResolver]

  [FilmService]

  [Repository<Film>]

  [MailService]
}


cloud {
    [TypeORM]
}

cloud {
    [nodemailer]
}

database "DB film" {
    [Tabelle film]
    [Tabelle schlagwort]
}

node {
    [Mailserver]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [FilmController]
[RequestLoggerMiddleware] ~~> [FilmResolver]

[FilmController] ..> [FilmService]
[FilmResolver] ..> [FilmService]
[FilmService] ..> [Repository<Film>]

[Repository<Film>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle film]
[TypeORM] ~~> [Tabelle schlagwort]

[FilmService] ..> [MailService]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

footer (c) Chiara Scheurer

@enduml