### Suche id, version und hauptdarsteller von allen Filme
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  filme {
    id
    version
    hauptdarsteller {
      rolle
    }
  }
}

### Suche Name, Version, Art und Hauptdarsteller von einem Film mit vorhandener Film-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($id: ID! = "1010") {
  film(id: $id) {
    name
    version
    genre
    hauptdarsteller{
      vorname,
      nachname
    }
  }
}

{
  "id": "1010"
}

### Suche Hauptdarsteller von einem Film mit nicht-vorhandener Film-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($id: ID! = "999999") {
  film(id: $id) {
    hauptdarsteller {
      vorname,
      nachname
    }
  }
}

{
  "id": "999999"
}

### Suche Art von Filme mit vorhandenem Hauptdarsteller
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($titel: String = "Alpha") {
  filme(hauptdarsteller: $titel) {
    genre
  }
}

{
  "hauptdarsteller": "Al Pacino"
}

### Suche Art, Schlagwoerter und Hauptdarsteller von Filme mit vorhandenem Hauptdarsteller
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($titel: String = "a") {
  filme(hauptdarsteller: $titel) {
    genre
    schlagwoerter
    hauptdarsteller {
      rolle
    }
  }
}

{
  "name": "a"
}

### Suche Art von Filme mit NICHT-vorhandenem Name
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($name: String = "Nichtvorhanden") {
  filme(name: $name) {
    genre
  }
}

{
  "name": "Nichtvorhanden"
}
