// Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//
// N e t z w e r k   -   V e r b i n d u n g   n o t w e n d i g
//

### Einloggen in der Rolle "admin", "mitarbeiter" und "kunde"
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "admin", password: "p") { token expiresIn roles }
}

### Einloggen in der Rolle "mitarbeiter" und "kunde"
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "alfred.alpha", password: "p") { token expiresIn roles }
}

### Einloggen in der Rolle "kunde"
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "dirk.delta", password: "p") { token expiresIn roles }
}

### Einloggen mit falschem Passwort
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "admin", password: "FALSCH") { token expiresIn roles }
}

### Neues Film anlegen
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  create(
    input: {
        name: "Journey to the center of the Earth",
        sprache: "en-EN",
        genre: ACTION,
        rating: 10,
        erscheinungsjahr: "2009-03-05",
        schlagwoerter: ["ADVENTURE", "FANTASIC"],
        hauptdarsteller: {
            rolle: "Trevor Anderson",
            vorname: "Brendan",
            nachname: "Fraser",
            alter: 54
        }
    }
  )
}

### Neues Film mit ungueltigen Daten anlegen
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  create(
    input: {
        name: "Invalid the Movie",
        sprache: "en-EN",
        genre: ACTION,
        rating: -9,
        erscheinungsjahr: "2010-07-29",
        schlagwoerter: ["IN", "VALID"],
        hauptdarsteller: {
            rolle: "Colin",
            vorname: "John",
            nachname: "Mannmuster",
            alter: 39
        }
    }
  )
}

### Vorhandenes Film aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    input: {
      id: "1000",
      version: 1,
      name: "Die Reise zum Mittelpunkt der Erde",
      sprache: "en-EN",
      genre: ACTION,
      rating: 10,
      erscheinungsjahr: "2009-03-05",
      schlagwoerter: ["ADVENTURE", "FANTASIC", "SCIFI"],
      hauptdarsteller: {
            rolle: "Trevor Anderson",
            vorname: "Brendan",
            nachname: "Fraser",
            alter: 55
        }
    }
  )
}

### Vorhandenes Film mit ungueltigen Werten aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    input: {
      id: 1000,
      version: 1,
      name: "Die Reise zum Mittelpunkt der Erde",
      sprache: "en-EN",
      genre: ACTION,
      rating: 10,
      erscheinungsjahr: "2009-03-05",
      schlagwoerter: ["ADVENTURE", "FANTASIC", "SCIFI"],
      hauptdarsteller: {
            rolle: "Trevor Anderson",
            vorname: "Brendan",
            nachname: "Fraser",
            alter: 55
        }
    }
  )
}

### Nicht-Vorhandenes Film aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    input: {
      id: "999999",
      version: 0,
      name: "WogWogWog",
      sprache: "en-EN",
      genre: ACTION,
      rating: 10,
      erscheinungsjahr: "2009-03-05",
      schlagwoerter: ["HALO"],
      hauptdarsteller: {
            rolle: "Chief",
            vorname: "Mas",
            nachname: "Ter",
            alter: 48
        }
    }
  )
}
